### Send post to node js 
POST http://localhost:8080/addweight
Content-Type: application/json


{
    "empName" : "juhi",
    "empWeight" : "80"

}

### Get 
GET http://localhost:8080/getemployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBOYW1lIjoiSnVoaSIsImlhdCI6MTYzODQzNjkxNCwiZXhwIjoxNjM4NDQwNTE0fQ.Aq4af4g-DsmQuuRuUeg9j8vZUeLa6gzN_LKid5kkeQM





###delete by  name 
DELETE http://localhost:8080/deletebyname
Content-Type: application/json

{
    "empName" : "Sally"
}

###Create employee
POST http://localhost:8080/addemployee
Content-Type: application/json

{
    "empName":"Param",
    "empPass":"18092001"
}


###Update Employee
PUT http://localhost:8080/updatedoc
Content-Type: application/json

{
    "empName":"Juhi",
    "empPass":"Juhi"

}

### Login User
POST http://localhost:8080/loginuser
Content-Type: application/json


{
    "empName" : "Juhi",
    "empPass" : "Juhi"

}